version: '3'
services:
  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Hexlet"
    networks:
      - internal
networks:
  internal:
    driver: bridge
